# Cours / 27-03-2023

## Théorie 
- Exceptions 
  - slides : [poo-08-exceptions](https://cyberlearn.hes-so.ch/pluginfile.php/4275559/mod_resource/content/0/poo-08-exception.pdf)

Le bloc `try` permet d'exécuter du code susceptible de déclencher des exceptions. 
Le bloc `catch` permet de récupérer les exceptions pour les traiter.

Le bloc `catch` peut être défini pour un type d'exception particulière.

```cpp

## Code
[codecollab](https://codecollab.io/@tmaulaz/poo23-exception)

### Exemple de code
```cpp
#include <iostream>

using namespace std;

void func_a(int val){
    cout << "Fonction a avant le throw" << endl;
    throw 5; // déclenche une exception de type int
    cout << "Fonction a après le throw" << endl;
}

int main(){

    try{
        cout << "Main avant appelle de la fonction A" << endl;
        func_a(0);
        cout << "Main après appelle de la fonction A" << endl;
    }
    catch(int a){ // récupère l'exception de type int
        cout << "Catch int dans la function main: " << a << endl;
    }
    catch(...){ // récupère toutes les autres exceptions
        cout << "Catch ... dans la function main: " << endl;
    }
}
``` 

# Labo et exercice
- UML du laboratoire cocktail

## Exercices :
4 : [exercices](https://github.com/tony-maulaz/poo-exercices/blob/main/ex90-exception.md)

